window.MNS_MOCK_REPORTS = [
  {
    task_id: "analysis-demo-600519",
    stock: { code: "600519", name: "贵州茅台", market: "cn" },
    status: "report_ready",
    action: "watch",
    confidence: "medium",
    summary: "趋势仍偏稳，等待更清晰的量价确认。",
    reasons: ["价格位于主要均线附近", "估值数据已进入上下文", "当前报告来自 Web 离线演示数据"],
    risks: [{ level: "medium", message: "短期波动可能放大，需结合真实数据复核" }],
    agent_views: [
      { agent: "TradingAgents market", conclusion: "价格结构保持韧性，但量能确认不足" },
      { agent: "TradingAgents news", conclusion: "公告与新闻未出现重大负面冲击" },
      { agent: "TradingAgents hot_money", conclusion: "资金参与度仍需等待放量确认" },
      { agent: "TradingAgents portfolio_manager", conclusion: "组合层面建议观察仓位，等待量价和事件共振" }
    ],
    data_sources: ["tencent", "eastmoney+cls+sina-bulletin"],
    engine_source: "tradingagents",
    engine_mode: "tradingagents",
    fallback_reason: null,
    data_gaps: ["fund_flow"],
    data_diagnostics: [
      { kind: "quote", source: "tencent", ok: true, error_type: null, error_message: null, fetched_at: null, is_stale: false },
      {
        kind: "deep_engine",
        source: "tradingagents",
        ok: true,
        selected_analysts: ["market", "social", "news", "fundamentals", "policy", "hot_money", "lockup"],
        provider: "minimax",
        deep_model: "MiniMax-M2.7",
        quick_model: "MiniMax-M2.7-highspeed",
        results_dir: "data/cache/tradingagents/results",
        cache_dir: "data/cache/tradingagents/cache",
        runtime_ms: 4820,
        context_snapshot: { events: [], gaps: ["fund_flow"] }
      }
    ],
    data_trust: {
      score: 82,
      level: "high",
      summary: "数据可信度较高，真实来源覆盖了行情、新闻和公告标题。",
      signals: ["真实行情来自腾讯", "新闻和公告已接入", "存在明确的结构化事件"],
      penalties: ["仍存在资金流缺口"],
      data_sources: ["tencent", "eastmoney+cls+sina-bulletin"],
      data_gaps: ["fund_flow"],
      diagnostics_ok: 1,
      diagnostics_failed: 0,
      engine_source: "tradingagents",
      engine_mode: "tradingagents",
      fallback_reason: null,
    },
    engine_telemetry: {
      runtime_ms: 4820,
      execution_path: "primary",
      cost_tier: "high",
      estimated_request_count: 1,
      engine_source: "tradingagents",
      engine_mode: "tradingagents",
      failure_type: null,
      failure_reason: null,
      notes: ["真实 TradingAgents 命中", "真实 TradingAgents 运行成功"],
    },
    engine_cost_guardrail: {
      status: "over_budget",
      summary: "真实 TradingAgents 运行超出默认成本预算，建议复核后再继续深度分析。",
      alerts: ["cost_tier>medium"],
      max_runtime_ms: 5000,
      max_request_count: 1,
      max_cost_tier: "medium",
      runtime_ms: 4820,
      estimated_request_count: 1,
      cost_tier: "high",
      engine_source: "tradingagents",
      engine_mode: "tradingagents",
    },
    risk_controls: {
      max_position_pct: 0.05,
      stop_loss_pct: 0.08,
      take_profit_pct: 0.15,
      time_horizon: "5-20 个交易日",
      rules: [
        { name: "confidence", level: "medium", message: "中等置信度设定仓位上限" },
        { name: "data_gaps", level: "medium", message: "存在资金流数据缺口，仓位上限降至 5%" }
      ],
      disclaimer: "本报告仅用于研究和复盘，不构成投资建议；任何交易决策需由用户自行承担风险。"
    },
    investment_plan: {
      direction: "watch",
      target_position_pct: 0.05,
      entry_conditions: ["价格确认站稳后再分批介入"],
      exit_conditions: ["跌破止损线", "核心事件逻辑失效", "目标收益达到"],
      stop_loss_pct: 0.08,
      take_profit_pct: 0.15,
      observation_window: "5-20 个交易日",
      review_conditions: ["每个交易日收盘后复核", "新增结构化事件后立即复核"],
      rationale: ["价格结构保持韧性，但量能确认不足", "资金流缺口仍需观察"],
      positive_evidence_summary: "正向证据主要来自标题与正文同时命中的事件。",
      negative_evidence_summary: "风险证据主要来自标题命中的风险事件。",
      risk_notes: ["资金流数据缺口存在，仓位需要保守"],
    },
    backtest: {
      task_id: "analysis-demo-600519",
      entry_date: "2026-07-01",
      exit_date: "2026-07-05",
      entry_price: 100,
      exit_price: 116,
      return_pct: 0.16,
      max_drawdown_pct: -0.02,
      holding_days: 4,
      exit_reason: "take_profit"
    },
    data_context: {
      stock: { code: "600519", name: "贵州茅台", market: "cn" },
      quote: { price: 1688, source: "tencent" },
      technicals: { ma5: 1660, ma10: 1625, ma20: 1588 },
      fundamentals: { pe_ttm: 28.5, pb: 9.1 },
      news: [{ title: "示例新闻：业绩保持稳定" }],
      events: [
        {
          event_type: "earnings_forecast",
          title: "示例公司发布2026年半年度业绩预告",
          source: "static",
          summary: "识别为业绩预告类事件，属于高优先级基本面信号。",
          confidence: "high",
          priority: "high",
          evidence_scope: "title+content",
          evidence_excerpt: "预计同比增长，公告口径保持稳健。",
          time: "2026-07-01",
          content: "预计同比增长",
          url: "",
          matched_keywords: ["业绩预告"]
        },
        {
          event_type: "share_repurchase",
          title: "示例公司发布股份回购方案",
          source: "sina-bulletin",
          summary: "识别为回购类事件，属于高优先级股东回报信号。",
          confidence: "medium",
          priority: "high",
          evidence_scope: "title",
          evidence_excerpt: "示例公司发布股份回购方案",
          time: "2026-07-01",
          content: "拟以自有资金回购部分股份",
          url: "",
          matched_keywords: ["股份回购"]
        },
        {
          event_type: "share_pledge",
          title: "控股股东股权质押进展公告",
          source: "sina-bulletin",
          summary: "识别为股权质押类事件，属于高优先级风险事件。",
          confidence: "medium",
          priority: "high",
          evidence_scope: "content",
          evidence_excerpt: "控股股东股权质押进展，质押比例上升。",
          time: "2026-07-01",
          content: "质押比例上升",
          url: "",
          matched_keywords: ["股权质押"]
        },
        {
          event_type: "share_increase",
          title: "控股股东拟增持公司股份",
          source: "sina-bulletin",
          summary: "识别为增持类事件，属于高优先级股东增持信号。",
          confidence: "medium",
          priority: "high",
          evidence_scope: "title+content",
          evidence_excerpt: "计划在未来 6 个月内增持不超过 2% 股份。",
          time: "2026-07-01",
          content: "计划在未来 6 个月内增持不超过 2% 股份",
          url: "",
          matched_keywords: ["增持"]
        }
      ],
      gaps: ["fund_flow"],
      diagnostics: []
    }
  },
  {
    task_id: "auto-fallback-demo-000001",
    stock: { code: "000001", name: "平安银行", market: "cn" },
    status: "report_ready",
    action: "watch",
    confidence: "low",
    summary: "真实 TradingAgents 未命中，已回退到工具驱动分析。",
    reasons: ["估值处于低位区间", "技术面仍缺少趋势突破", "TradingAgents auto 模式失败后已回退到工具驱动分析"],
    risks: [{ level: "low", message: "报告使用离线演示数据，不构成投资建议" }],
    agent_views: [
      { agent: "Fundamentals Analyst", conclusion: "估值具备观察价值，但盈利弹性仍需验证" },
      { agent: "News Analyst", conclusion: "缺少新的高置信事件驱动" }
    ],
    data_sources: ["static"],
    engine_source: "tool-driven",
    engine_mode: "auto",
    fallback_reason: "TradingAgents 执行失败: Missing credentials",
    data_gaps: ["news"],
    data_diagnostics: [
      { kind: "news", source: "static", ok: false, error_type: "MissingData", error_message: "离线演示新闻不足", fetched_at: null, is_stale: false },
      {
        kind: "deep_engine",
        source: "tradingagents",
        ok: false,
        selected_analysts: ["market", "social", "news", "fundamentals", "policy", "hot_money", "lockup"],
        provider: "openai",
        deep_model: "gpt-5.4",
        quick_model: "gpt-5.4-mini",
        runtime_ms: 0,
        error_type: "MissingCredentials",
        error_message: "Missing credentials",
        context_snapshot: { events: [], gaps: ["news"] }
      },
      { kind: "deep_engine", source: "tool-driven", ok: true, error_type: "MissingCredentials", error_message: "Missing credentials", fetched_at: null, is_stale: false }
    ],
    data_trust: {
      score: 52,
      level: "low",
      summary: "数据可信度偏低，新闻缺口和离线来源都会影响结论可靠性。",
      signals: ["估值和价格数据可用"],
      penalties: ["新闻数据缺口", "主要来源为静态演示数据", "缺少真实深度引擎消费痕迹"],
      data_sources: ["static"],
      data_gaps: ["news"],
      diagnostics_ok: 0,
      diagnostics_failed: 1,
      engine_source: "tool-driven",
      engine_mode: "auto",
      fallback_reason: "TradingAgents 执行失败: Missing credentials",
    },
    engine_telemetry: {
      runtime_ms: 12,
      execution_path: "quick",
      cost_tier: "low",
      estimated_request_count: 1,
      engine_source: "tool-driven",
      engine_mode: "auto",
      failure_type: "MissingCredentials",
      failure_reason: "Missing credentials",
      notes: ["真实 TradingAgents 未命中", "已回退到工具驱动分析"],
    },
    engine_cost_guardrail: {
      status: "ok",
      summary: "引擎成本处于预算内。",
      alerts: [],
      max_runtime_ms: 5000,
      max_request_count: 1,
      max_cost_tier: "medium",
      runtime_ms: 12,
      estimated_request_count: 1,
      cost_tier: "low",
      engine_source: "tool-driven",
      engine_mode: "auto",
    },
    risk_controls: {
      max_position_pct: 0.05,
      stop_loss_pct: 0.08,
      take_profit_pct: 0.15,
      time_horizon: "5-20 个交易日",
      rules: [
        { name: "confidence", level: "low", message: "低置信度限制仓位" },
        { name: "data_gaps", level: "medium", message: "存在新闻数据缺口，仓位上限降至 5%" }
      ],
      disclaimer: "本报告仅用于研究和复盘，不构成投资建议；任何交易决策需由用户自行承担风险。"
    },
    investment_plan: {
      direction: "watch",
      target_position_pct: 0.05,
      entry_conditions: ["等待更明确的趋势或事件确认"],
      exit_conditions: ["不满足入场条件", "证据仍不足以形成有效计划"],
      stop_loss_pct: 0.08,
      take_profit_pct: 0.15,
      observation_window: "5-20 个交易日",
      review_conditions: ["每日复核一次", "新的高置信事件出现时复核"],
      rationale: ["估值处于低位区间", "技术面仍缺少趋势突破", "新闻上下文较少"],
      positive_evidence_summary: "正向证据主要来自标题命中的弱信号。",
      negative_evidence_summary: "风险证据主要来自新闻缺口和离线回退。",
      risk_notes: ["新闻数据缺口较大，计划只能维持观察仓位"],
    },
    backtest: {
      task_id: "analysis-demo-000001",
      entry_date: "2026-07-01",
      exit_date: "2026-07-05",
      entry_price: 100,
      exit_price: 96,
      return_pct: -0.04,
      max_drawdown_pct: -0.06,
      holding_days: 4,
      exit_reason: "time_exit"
    },
    data_context: {
      stock: { code: "000001", name: "平安银行", market: "cn" },
      quote: { price: 10.8, source: "static" },
      technicals: { ma5: 10.6, ma10: 10.4, ma20: 10.2 },
      fundamentals: { pe_ttm: 5.8, pb: 0.62 },
      news: [],
      events: [],
      gaps: ["news"],
      diagnostics: []
    }
  }
];
